added queryParams to changes route
ember-learn/upgrade-guide pull request #61
Opened 2020-10-21 01:40 UTC by takshch

# Description
- Removed queryParams from index route.
- Added queryParams to changes route.
- No change in url of index route when we select or change ember version (fromVersion, toVersion).
- When click on the 'Find Changes' button, we will be redirected to changes route with queryParams.

# Acceptance test for index route
- When we visit the index route, we see the form for selecting Ember versions ✅
- When we select Ember versions, the URL does not change ✅
- When we submit the form, we are redirected to the changes route ✅
- When we submit the form, we see the features and deprecations that occurred ✅
- When we submit the form with fromVersion greater than toVersion, we see 0 features and 0 deprecations ✅

2020-10-21 14:09 UTC, ijlee2 commented
Thanks, @takshch. I'll have a look later tonight.

2020-10-22 01:15 UTC, ijlee2 commented on app/controllers/index.js
> +    });
**suggestion (soft-blocking):**

The controller doesn't need its copy of `fromVersion` and `toVersion`, now that we have a form component. Let's delete lines 9 and 10, and update lines 11-16 to:

```suggestion
    this.router.transitionTo('changes', {
      queryParams: {
        fromVersion,
        toVersion,
      },
    });
```

2020-10-22 01:17 UTC, ijlee2 commented on tests/acceptance/index-test.js
> +  test('When we submit the form with fromVersion greater than toVersion, we see 0 features and 0 deprecations', async function (assert) {
**praise:**

Thanks for checking this edge case!

2020-10-22 01:20 UTC, ijlee2 requested changes
@takshch Thanks for working on this issue! I checked the app locally and everything worked well. I thought you did an exceptional job with writing tests. ✨

Before I merge your pull request, I'd like to see a couple of changes:

- Remove references to `this.fromVersion` and `this.toVersion` from the `index` controller
- In the `index` route template, can you remove the "form's output" (lines 7-39)? (The user is to see the output in `changes` route now.)

2020-10-22 10:27 UTC, takshch commented
Required changes are made and pushed into the code. Please review it Sir.

2020-10-22 10:28 UTC, takshch commented on app/controllers/index.js
> +    });
Yes. It's mistake. and it's fixed now.

2020-10-22 12:38 UTC, takshch commented
@ijlee2 Sorry for unexpected hbs linting changes. Could you please tell me when to  and when not to use hbs linter.

2020-10-22 12:41 UTC, ijlee2 commented
@takshch No problem. It seemed like you may have an IDE that auto-fixes linting errors.

For pull requests for open source, unless the issue asked you to fix linting errors, I'd try to preserve the code formatting (make few code changes to help reduce noise in a code review).

2020-10-22 12:42 UTC, ijlee2 approved these changes

2020-10-22 12:42 UTC, merged

2020-10-23 14:07 UTC, takshch commented
@ijlee2 Could you please add label of "hacktoberfest-accepted"

2020-10-23 14:33 UTC, ijlee2 commented
Hi, @takshch. If you visit your [Hacktoberfest dashboard](https://hacktoberfest.digitalocean.com/profile), I think you will see a timer next to this pull request.

The [updated rules](https://hacktoberfest.digitalocean.com/hacktoberfest-update) indicate that there's a **14-day waiting period** before you see a checkmark next to the pull request. Because I already added `Hacktoberfest` topic to this repo and approved your pull request, you should be good to go. 🎊

![updated_rules](https://user-images.githubusercontent.com/16869656/97016735-b67a6000-1512-11eb-916e-5c71390bbf8d.png)