Issue 91
ember-learn/upgrade-guide pull request #95
Opened 2022-03-28 01:04 UTC by MehulKChaudhari

This PR resolves #91

2022-03-31 15:52 UTC, jenweber commented on app/components/ember-versions-form.hbs
> +  {{/unless}}
We need to make sure screen reader users know that there was a problem with their selections. Here's one way to do that https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Alert_Role

```suggestion
<div role="alert">
  {{#unless this.isValid}}
    <p class="mt-2">To version should be bigger than From version</p>
  {{/unless}}
</div>
```

2022-03-31 16:13 UTC, MehulKChaudhari commented on app/components/ember-versions-form.hbs
> +    <p class="mt-2">To version should be higher than From version</p>
Also @jenweber this text color is black. I think it should be red or yellow. what do you think? 

I was not able to find a classname to change the color of this <p> tag in ember styleguides documentation.

2022-04-03 17:25 UTC, MehulKChaudhari commented on app/components/ember-versions-form.hbs
> +    <p class="mt-2">To version should be higher than From version</p>
Hey @jenweber Can you please help me here.

2022-04-08 23:19 UTC, locks commented
@jenweber can you take a look again?

2022-04-20 03:16 UTC, jenweber approved these changes
I tried to figure out a color variation, and I don't think that is supported in the component library. Let's merge this as-is. It is a great UX improvement, and at least the black text will pass color contrast.

Thanks for your work on this @MehulKChaudhari !

2022-04-20 03:17 UTC, jenweber commented
@MehulKChaudhari There is a test that needs to be updated. It should assert instead that your error message shows up:

>  not ok 9 Chrome 100.0 - [99 ms] - Acceptance | index: When we submit the form with fromVersion greater than toVersion, we see 0 features and 0 deprecations

Let me know if you need any help with this.

2022-04-20 05:07 UTC, MehulKChaudhari commented
> @MehulKChaudhari There is a test that needs to be updated. It should assert instead that your error message shows up:
> 
> > not ok 9 Chrome 100.0 - [99 ms] - Acceptance | index: When we submit the form with fromVersion greater than toVersion, we see 0 features and 0 deprecations
> 
> Let me know if you need any help with this.

@jenweber I have to assert that button is disabled in this case and error message shows up right?

2022-04-20 06:09 UTC, ijlee2 commented on app/components/ember-versions-form.js
> +  }
Hi, @MehulKChaudhari. I think what we'll want to have in the component class is a **getter**.

```js
get areVersionsValid() {
  return VERSIONS.indexOf(this.fromVersion) < VERSIONS.indexOf(this.toVersion);
}
```

Because `fromVersion` and `toVersion` are tracked properties, the getter will be recomputed whenever either tracked property changes its value. (No need for lines 10, 32, and 37.)

However, we want the getter to evaluate to `true` when either `fromVersion` or `toVersion` is `undefined`. So we will want to introduce an **early exit** to the getter.

```js
get areVersionsValid() {
  const { fromVersion, toVersion } = this;

  if (!fromVersion || !toVersion) {
    return true;
  }

  return VERSIONS.indexOf(fromVersion) < VERSIONS.indexOf(toVersion);
}
```

The 2nd solution above, however, still has the issue of **order dependency**. If we change the order of array elements in `VERSIONS`, the getter can potentially return an incorrect value. I think we may be using already a library to help us compare version numbers? Can you look into using the library instead?

2022-04-20 06:11 UTC, ijlee2 commented on tests/integration/components/ember-versions-form-test.js
> +    assert.false(button.disabled);
If there isn't a test selector already, can we provide one so that we can write (using QUnit DOM),

```ts
assert.dom('[data-test-button="Submit"]').isDisabled();
```

2022-04-20 06:11 UTC, ijlee2 commented on tests/integration/components/ember-versions-form-test.js
> +    assert.true(button.disabled);
```js
assert.dom('[data-test-button="Submit"]').isDisabled();
```

2022-04-20 06:13 UTC, ijlee2 requested changes
@MehulKChaudhari Thank you for looking into a bug fix. I think your first attempt is good and liked that you provided tests to prevent a regression in the future.

I'd like us to use a getter (for autotracking in Ember to work) and update how tests are written to improve maintainability. Could you look into my review comments? If you have questions, feel free to ask them.

2022-04-20 10:51 UTC, MehulKChaudhari commented on tests/integration/components/ember-versions-form-test.js
> +    assert.false(button.disabled);
I didn't know we can do it this way. Thanks for the review @ijlee2 I learned something new today.

2022-04-20 10:52 UTC, MehulKChaudhari commented on tests/integration/components/ember-versions-form-test.js
> +    assert.true(button.disabled);
Done

2022-04-20 15:21 UTC, MehulKChaudhari commented on app/components/ember-versions-form.js
> +  }
Sounds good. I have made the suggested changes.

2022-04-20 15:36 UTC, ijlee2 approved these changes

2022-04-20 15:37 UTC, merged